### ISSUE TITLE
Create 'CAMT page' feature -3

### ISSUE THREAD

**Issue by ThanapongYamkamol642115022** [ThanapongYamkamol642115022/devopslab04#6]
Check out index link commit
Create feature-CAMT-page from development branch
Add CAMT info
Create link to camt.html in index.html
Commit as feature

**Comment by ThanapongYamkamol642115022** [comment]
create camt page and add link to index

**Comment by thanaponglaboratory** [comment]
a49f5889c9770e8d7ea206bcb4d0ae6c80f6a533

a54d250bd70e0a45004436f473bb1a8b7f58ee74
